# Generated by Django 5.2.3 on 2025-06-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='original_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
